# Tokenize
# python preprocess/010_reviews.py raw/yelp_test_set_review.csv data/test_review_stemmed.csv
# python preprocess/010_reviews.py raw/yelp_academic_dataset_review.csv data/train_review_stemmed.csv 

#Combine files
rm data/combined.csv
cat data/train_review_stemmed.csv data/train_review_stemmed.csv > data/combined.csv

#Convert to vw
python preprocess/2vw.py data/combined.csv data/combined.vw

#Split 
split -l 229907 data/combined.vw 

mv data/xaa data/train.vw
mv data/xab data/test.vw
#Train vw
vw -d data/train.vw -c -f model --passes 20
vw -t -d data/test.vw -c -i model -p data/p2.txt